### ISSUE TITLE
Does it work to mesh warp like photoshop's transform warp tool?

### ISSUE THREAD

**Issue by milqnomadu** [jerry-eldridge/pywarp#1]
Does it work to mesh warp like photoshop's transform warp tool?

**Comment by jerry-eldridge** [comment]
I was not thinking of "photoshop's transform warp tool" when I wrote it if that was around back then. Instead pywarp is very simple and I wrote it one day long ago and I used the C bindings for python back then. The python2 code and C++ source code outline the algorithm for a pseudocode. This library is very old and I have shifted most of my programming jgeutil3 instead. I was thinking of (group) "actions on a set" (abstract algebra) and applying that action in an operator on a set much like a Rubik's cube has permutations apply on the set of the Rubik's cube. And I was also thinking of warping space as in General Relativity or Riemannian manifolds.

**Comment by milqnomadu** [comment]
Hey Jerry thank you for the response. Would it be absolutely impossibile to be able to communicate with you via email about some advices I'd want to ask you? milqnomadu@gmail.com

Hope you have a wonderful rest of the day!

**Comment by jerry-eldridge** [comment]
I added NEW_linux to the pywarp repository which correctly builds an Ubuntu Linux warp.so file which is imported into python3. A number of changes were made to adapt for Python3. It works.

**Comment by milqnomadu** [comment]
Hey Jerry, I have absolutely no idea what that means, you're way too clever for me lol. Wanted to connect via email if I don't disturb, just want to explain the outcome I'm trying to achieve and I'm having problems with

**Comment by jerry-eldridge** [comment]
Steps in Ubuntu Linux on WSL2 (Windows Subsystem for Linux 2). See online references for how to set up Ubuntu Linux on WSL2 under Windows.
Ubuntu linux shell:
1. git clone https://github.com/jerry-eldridge/pywarp.git
2. cd pywarp
3. cd NEW-linux
4. make
and one needs whatever required libraries. All the script does is to warp an image. The steps are more
complicated on Windows with Visual Studio so easiest to explain was this linux version. Originally, I used Python2
and now Python3 is used in jgeutil3 repository. I cannot explain General Relativity and Riemannian Manifolds or the other details. See code for the explanation.

**Comment by jerry-eldridge** [comment]
It looks like the issue is closed. If you have any other questions feel free to ask.

**Comment by milqnomadu** [comment]
Hi Jerry, although you closed the issue you haven't respond nor to my initial nor to my second question. Does this repo help me replicate Photoshop's warp tool?
![wanted-ezgif com-video-to-gif-converter](https://github.com/jerry-eldridge/pywarp/assets/151824174/116d0785-b1d3-4d05-b210-69216554a0db)

**Comment by jerry-eldridge** [comment]
This seems to be an issue between a producer and a consumer. pywarp produces and users consume. However, photoshop is another producer unrelated to this producer of pywarp. You are free to consume the product, pywarp, as you wish according to appropriate license conditions and above the steps on how to run the software were presented. It is difficult to get work done with such pong match back and forth, so I closed the issue having answered your issue as best as I could. pywarp is not related to photoshop.

**Comment by milqnomadu** [comment]
Hey jerry, I know pywarp is not related to photoshop. I've just attached that gif as an example asking if a type of mesh warp like that would be possible using pywarp and a gui. I have no idea what you're talking about regarding "This seems to be an issue between a producer and a consumer". Just a simple quick Yes or No question
